language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_script:
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib.git spec/fixtures/modules/stdlib'
env:
  - PUPPET_VERSION=2.6.2
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.0.2
